### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by macgyverfuerarme** [Schury1998/WiFiScam-CaptivePortal-M5StickCPlus#1]
I have problems finding the correct libraries. Especially with the WiFi.h . Which version did you use? Possible to link the correct libraries? Great projekt btw

**Comment by Schury1998** [comment]
Have you made step 4? --> Tools - Manage Libarys... - Type in M5StickCPlus and install the M5StickCPlus by M5Stack
Then the libarys should be automatic added in the arduino folder: https://github.com/espressif/arduino-esp32/tree/master/libraries

**Comment by macgyverfuerarme** [comment]
thx .... had double wifi.h files with different versions. my fault. sorry.
