### ISSUE TITLE
reading back Emails and passwords

### ISSUE THREAD

**Issue by tompusey** [Schury1998/WiFiScam-CaptivePortal-M5StickCPlus#2]
This is probably a dumb question but how do you read back the emails and passwords from the EEPROM?

**Comment by Schury1998** [comment]
> This is probably a dumb question but how do you read back the emails and passwords from the EEPROM?

Connect your mobilephone/pc with the wifi. Open the Browser an type in 8.8.4.4/pass.

**Comment by tompusey** [comment]
Yep, that makes sense now I look at the arduino file, Thanks for the help!
