### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by Hakcer274** [Schury1998/WiFiScam-CaptivePortal-M5StickCPlus#3]
Sorry, but how do I compile the code to arduino ide?

**Comment by Schury1998** [comment]
Did you follow the steps:

To implement the M5CStickCPlus to the Arduino IDE:

1.)
Open the IDE or first install from the official website

2.)
File - Preferences - Additional boards manager URLs: https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json

3.)
Tools - Board - Boards Manager... and type in M5Stack - install the Boards

4.)
Tools - Manage Libarys... - Type in M5StickCPlus and insatll the M5StickCPlus by M5Stack

5.)
Tools - Board and select the M5StickCPlus

6.)
Plug in the M5StickCPlus - Tools - Port and selct the Port

7.)
Complie and Upload


-> What the compiler error you get?

**Comment by Hakcer274** [comment]
This seems like a dumb question, but do you just copy the code into the codespace after step 6? I am new to coding and just trying to figure things out:)

**Comment by Schury1998** [comment]
Copy the whole Folder WiFiScam and open it wird die Arduino IDE. You need both files the .ino and the .h

**Comment by Hakcer274** [comment]
thanks:)
